name: Bug report
description: Report a reproducible bug
title: '[Bug]: '
labels: ['bug']
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: What did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: textarea
    id: env
    attributes:
      label: Environment
      placeholder: |
        - Node:
        - pnpm:
        - WeChat DevTools:
        - OS:
    validations:
      required: true
